POST http://localhost:3000/SignUp
content-type: application/json

{
    "username": "test",
    "password": "1234",
    "email": "test",
    "role": "2"
}

###
POST http://localhost:3000/SignIn
content-type: application/json

{
    "username": "punonly",
    "password": "21072643"
}